package com.phantomwing.calamari.neoforge.client;

import net.neoforged.fml.ModContainer;
import net.neoforged.neoforge.client.gui.ConfigurationScreen;
import net.neoforged.neoforge.client.gui.IConfigScreenFactory;

/**
 * Client-only bootstrap for Calamari on NeoForge.
 *
 * <p><b>Why this is a separate class.</b> It references client-only types
 * ({@link ConfigurationScreen} → {@code Screen}, {@link IConfigScreenFactory}).
 * If that lambda lived in the {@code @Mod} class, the JVM would resolve those
 * types when the class is verified — forcing client classes to load — and
 * NeoForge's dedicated-server class loader hard-rejects them ("invalid dist
 * DEDICATED_SERVER"), crashing the server during mod construction even behind a
 * runtime {@code isClient()} guard (verification happens before the branch runs).
 * Isolating it here and calling {@link #init} via {@code invokestatic} keeps the
 * client types off the server entirely.</p>
 */
public final class CalamariNeoForgeClient {
    private CalamariNeoForgeClient() {
    }

    public static void init(ModContainer container) {
        // Registers the in-game config screen (Mods -> Calamari -> Config),
        // auto-generated by NeoForge from the ModConfigSpec.
        container.registerExtensionPoint(IConfigScreenFactory.class, ConfigurationScreen::new);
    }
}
