modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/PhantomWing/Calamari/issues"
license = "MIT License"

[[mods]]
modId = "calamari"
version = "${version}"
displayName = "Calamari"
displayURL = "https://github.com/PhantomWing/Calamari"
logoFile = "icon.png"
authors = "PhantomWing"
description = '''
Squids and glow squids drop calamari, a vanilla-friendly seafood you can cook, trade, and eat.
'''

[[dependencies.calamari]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.calamari]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.calamari]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
